{% set name = "higra" %}
{% set version = "0.6.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/higra/Higra/archive/refs/tags/{{ version }}.tar.gz
  sha256: 541441caada9b613141571608d07d4ad6f1f8b47123a9a3786863c4d4ffc9b2a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - numpy

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - higra

about:
  home: https://github.com/higra/Higra
  license: CeCILL-B
  license_file: LICENSE
  summary: 'Hierarchical graph analysis library'
  doc_url: https://higra.readthedocs.io
  dev_url: https://github.com/higra/Higra

extra:
  recipe-maintainers:
    - JoOkuma
    - PerretB
